name: fibermorph_env
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1
  - certifi=2019.11.28=py36_0
  - freetype=2.9.1
  - intel-openmp=2019.4
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pip=20.0.2=py36_1
  - pyparsing=2.4.6
  - python=3.6.10
  - python-dateutil=2.8.1
  - setuptools=45.2.0
  - six=1.14.0=py36_0
  - sqlite=3.31.1
  - tk=8.6.8
  - tornado=6.0.3
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - asgiref==3.2.3
    - cycler==0.10.0
    - decorator==4.4.1
    - django==3.0.3
    - image==1.5.28
    - imageio==2.8.0
    - joblib==0.14.1
    - networkx==2.4
    - numpy==1.18.1
    - opencv-python==4.2.0.32
    - pandas==1.0.1
    - pillow==7.0.0
    - pytz==2019.3
    - pywavelets==1.1.1
    - rawpy==0.14.0
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - sqlparse==0.3.0
